// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyLV9Rayv6p3Pt5-43P9LJEipgN_8qy44',
    appId: '1:716093357408:web:f9d0e1dc5c17856d293205',
    messagingSenderId: '716093357408',
    projectId: 'notice-board-f5359',
    authDomain: 'notice-board-f5359.firebaseapp.com',
    storageBucket: 'notice-board-f5359.appspot.com',
    measurementId: 'G-7ZEPZDWDXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDImgtw4Rppu9NibSs-GHU5IcQ4FPoMV9U',
    appId: '1:716093357408:android:bd91973b6e81c788293205',
    messagingSenderId: '716093357408',
    projectId: 'notice-board-f5359',
    storageBucket: 'notice-board-f5359.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB35MEA_N2rOP8BY-ncQw5Mf3uLZu4effg',
    appId: '1:716093357408:ios:8227394c9031f212293205',
    messagingSenderId: '716093357408',
    projectId: 'notice-board-f5359',
    storageBucket: 'notice-board-f5359.appspot.com',
    iosBundleId: 'com.example.flutterProject1',
  );
}
